apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
        environment: dev
        version: v1
spec:
    image: nginx:latest
    resources:
        limit:
            cpu: 125m
            memory: 1Gi
