apiVersion: v1
kind: ConfigMap
metadata:
    name: db-config2
data:
    db-host: "localhost.example.com"
    db-port: "3306"
    db-name: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: multi-con-01
spec:
    selector:
        matchLabels:
            app: multi-con-01
    template:
        metadata:
            name: multi-con-01
            labels:
                app: multi-con-01
        spec:
            containers:
                - name: container1
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  envFrom:
                      - configMapRef:
                            name: db-config2      
                - name: container2       
                  image: ubuntu:latest
                  command:
                      - "/bin/bash"
                      - "-c"
                  args:
                      - "sleep 5000"
                  env:
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: db-config2
                                key: db-host
                      - name: DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: db-config2
                                key: db-port
                      - name: DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: db-config2
                                key: db-name
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                key: db_user
                                name: db-creds
                  envFrom:
                    - secretRef:
                        name: db-creds
