apiVersion: v1
kind: Secret
metadata:
    name: db-creds
type: Opaque
immutable: true
stringData:
    db_scope: local # Override stuff in data
data:
    db_user: cm9vdAo=
    db_password: cGFzczQwNAo=
    db_role: YWRtaW4K
