apiVersion: v1
kind: ConfigMap
metadata:
  name: twilio-numbers
data:
  TO: '+5543999287543'
  FROM: '+14153016252'
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-secrets
type: Opaque
data:
  ACCOUNT_SID: QUM4NWQzZmU3Yzc2MDkwMWY2ZmM2Nzc3YWNiOWI2YzRmMwo=
  AUTH_TOKEN: MTJhNDA4ZTM2OTBkMjhlYzZiZjE4YWRiMzgxMzVhMzEK
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nubank-invoice
spec:
  schedule: "0 0 4 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nubank-invoice
            image: personal-notications:0.0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: twilio-secrets
            - configMapRef:
                name: twilio-numbers
            env:
              - name: MESSAGE
                value: Pay you nubank invoice
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ligue
spec:
  schedule: "0 0 1,2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ligue
            image: personal-notications:0.0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: twilio-secrets
            - configMapRef:
                name: twilio-numbers
            env:
              - name: MESSAGE
                value: Pay internet LIGUE, R$ 99,00
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: light
spec:
  schedule: "0 0 15,16 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: light
            image: personal-notications:0.0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: twilio-secrets
            - configMapRef:
                name: twilio-numbers
            env:
              - name: MESSAGE
                value: Pay your LIGHT bill
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: water
spec:
  schedule: "0 0 22,23 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: water
            image: personal-notications:0.0.1
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: twilio-secrets
            - configMapRef:
                name: twilio-numbers
            env:
              - name: MESSAGE
                value: Pay your WATER bill
          restartPolicy: Never


