apiVersion: apps/v1
kind: Deployment
metadata:
    name: box0
spec:
    replicas: 1
    selector:
        matchLabels:
            app: box0
    template:
        metadata:
            name: box0
            labels:
                app: box0
        spec:
            containers:
                - name: box
                  image: ubuntu:latest
                  command: 
                    - "/bin/bash"
                    - "-c"
                  args:
                    - 'declare -i count; until [ $count -eq 30 ]; do echo "Sleeping before create $count"; count+=1; sleep 1; done; touch /tmp/debug; sleep 3600'
                  readinessProbe:
                    exec:
                        command:
                            - "/bin/bash"
                            - "-c"
                            - "[ -f /tmp/debug ]"
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 5
                    failureThreshold: 1
                    successThreshold: 1
                  livenessProbe:
                    exec:
                        command:
                            - "/bin/bash"
                            - "-c"
                            - "[ -f /tmp/debug ]"
                    initialDelaySeconds: 30
                    periodSeconds: 2
                    timeoutSeconds: 1
                    failureThreshold: 3
                    successThreshold: 1
