#  Warning  VolumeFailedDelete  43s (x2 over 3m47s)  persistentvolume-controller  error getting deleter volume plugin for volume "nfs-pv": no deletable volume plugin matched
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    release: stable
    environment: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/"
    server: 10.104.19.238