apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  selector:
    app: nfs
  ports:
  - port: 2049
    name: nfs
  - port: 20048
    name: mountd
  - port: 111
    name: rpcbind
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
spec:
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: myapp
        image: k8s.gcr.io/volume-nfs:0.8
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true