apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
spec:
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: myapp
        image: k8s.gcr.io/volume-nfs:0.8 # This image mount the nfs server in /exports
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true