apiVersion: v1
kind: ConfigMap
metadata:
    name: db-config
data:
    db-config: |
        db-host=localhost.example.com
        db-port=3306
        db-name=k8s-objects

    db-host: "localhost.example.com"
    db-port: "3306"
    db-name: "k8s-objects"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ubuntu01
spec:
    selector:
        matchLabels:
            app: ubuntu01
    replicas: 2
    template:
        metadata:
            name: ubuntu01
            labels:
                app: ubuntu01
        spec:
            containers:
                - name: ubuntu
                  image: ubuntu:latest
                  command:
                      - "/bin/bash"
                      - "-c"
                  args:
                      - "sleep 5000"
                  volumeMounts:
                      - name: db-config
                        mountPath: /db/config

            volumes:
                - name: db-config
                  configMap:
                    name: db-config
                    defaultMode: 0777
                    items:
                        - key: "db-host"
                          path: "db.config.old"
                        - key: "db-port"
                          path: "db.config.old"
                        - key: "db-name"
                          path: "db.config.old"
                        - key: "db-config"
                          path: "db.config"
