apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-1
    labels:
        environment: dev
spec:
    selector:
        matchLabels:
            tier: middleware
    template:
        metadata:
            labels: 
                tier: middleware
        spec:
            containers:
                - name: busyman
                  image: busybox:latest
