apiVersion: v1
kind: Pod
metadata:
    name: httpd
    namespace: default
    labels:
        app: httpd
spec:
    containers:
        - name: httpd
          image: httpd:alpine
          ports:
              - containerPort: 80
                name: http
---
apiVersion: v1
kind: Service
metadata:
    name: httpd-svc
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: httpd
