apiVersion: v1
kind: Pod
metadata:
    name: network-utils
    labels:
        app: network-utils
spec:
    containers:
        - name: net
          image: ubuntu:latest
          command:
              - "/bin/bash"
              - "-c"
          args:
              - "sleep 3600"
