apiVersion: v1
kind: ConfigMap
metadata:
    name: megadata
data:
    CREATED_BY: octocat
    OWNER: God
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx01-deployment
spec:
    selector:
        matchLabels:
            app: nginx01
    template:
        metadata:
            name: nginx01
            labels: 
                app: nginx01
        spec:
            containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  env:
                      - name: CREATED_BY
                        valueFrom:
                            configMapKeyRef:
                                key: CREATED_BY
                                name: megadata
                  envFrom:
                      - configMapRef:
                            name: megadata
