apiVersion: v1
kind: Pod
metadata:
    name: redis02
    namespace: finance
    labels:
        tier: db
spec:
    containers:
        - name: redis
          image: redis:alpine
          ports:
              - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: redis-service
    namespace: finance
spec:
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
          protocol: TCP
    selector:
        tier: db
   
