apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs-1
    labels: 
        environment: dev
spec:
    selector:
        matchLabels:
            tier: frontend
    template: 
        metadata:
            labels:
                tier: frontend
        spec:
            containers:
                - name: nginx-pod
                  image: nginx:latest
