apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-with-command
spec:
    containers:
        - name: ubuntu
          image: ubuntu:latest
          command: 
            - "/bin/bash"
            - "-c"
          args:
            - "sleep 5000"
