apiVersion: v1
metadata:
    name: webapp-color
kind: ConfigMap
data:
    COLOR: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-color-deployment
spec:
    selector:
        matchLabels:
             app: webapp-color
    template:
        metadata:
            labels:
                app: webapp-color
        spec:
            containers:
                - name: webapp
                  image: nginx:latest
                  env:
                      - name: VERSION
                        value: v1
                      - name: COLOR
                        valueFrom:
                            configMapKeyRef:
                                key: COLOR
                                name: webapp-color

