# Stress test for randomnumber/version 
# while true; do echo "$(curl -SsL internal-randomnumber.dev.svc.cluster.local)" >> testsresults && echo "$(curl -SsL internal-randomnumber.dev.svc.cluster.local/version)" >> testsresults; done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: green
  name: randomnumber-green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: randomnumber
  strategy: {}
  template:
    metadata:
      labels:
        app: randomnumber
        environment: green
    spec:
      containers:
      - image: randomnumberapp:0.0.2
        name: randomnumber
        env:
          - name: PORT
            value: '80'
          - name: VERSION
            value: '0.0.2'
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          requests:
            memory: 500Mi
            cpu: 125m
          limits:
            memory: 1Gi
            cpu: 250m