apiVersion: v1
kind: Service
metadata:
  namespace: prod
  labels:
    app: internal-randomnumber
    environment: dev
  name: internal-randomnumber
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: randomnumber