apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-randomnumber
    environment: test
  name: external-randomnumber
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: randomnumber
    environment: blue # Switch to blue/green